apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hsd-zone-server.fullname" . }}
  labels:
    {{- include "hsd-zone-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hsd-zone-server.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "hsd-zone-server.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: 53
              protocol: TCP
              hostPort: 53
          env:
          - name: ZONE
            value: {{ .Values.zone }}.
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: zonefile
            mountPath: /app/zone
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: zonefile
        configMap:
          name: zonefile